import { AgentTemplate } from '../../types';

export const AGENT_TEMPLATES: AgentTemplate[] = [
  // ─── Corretora de Seguros ───────────────────────────────────────────────────
  {
    id: 'corretora_seguros',
    segment: 'corretora_seguros',
    name: 'Corretora de Seguros Auto',
    description: 'Agente especializado em vendas consultivas de seguro automóvel via WhatsApp. Coleta documentos, calcula cotações e fecha propostas.',
    version: 1,
    publishedAt: '2026-05-16T00:00:00.000Z',
    publishedBy: 'platform',
    defaultPersona: {
      name: 'Ana',
      role: 'Consultora de Seguros',
      tone: 'amigável, consultiva e direta',
      usesFormalTreatment: false,
    },
    defaultSalesBlocks: {
      quebra_de_gelo: 'Inicie com uma saudação calorosa e personalize com o nome do cliente quando disponível. Demonstre que você já sabe o motivo do contato e mostre que vai facilitar o processo.',
      primeiro_atendimento: 'Demonstre expertise no mercado de seguros. Mencione que trabalha com múltiplas seguradoras para conseguir o melhor preço. Transmita confiança e agilidade — o cliente não precisa ligar para vários lugares.',
      reducao_atrito: 'Quando o cliente hesitar em enviar documentos, explique que é apenas para calcular o valor exato. Normalize o processo: "é rápido, menos de 1 minuto". Mencione segurança e privacidade dos dados.',
      gatilhos_mentais: 'Use escassez suave (promoções com prazo), prova social (número de clientes atendidos), e autoridade (parceria com as maiores seguradoras do Brasil). Nunca invente dados.',
      objecoes: 'Para "está caro": compare com o custo de um sinistro sem seguro. Para "vou pensar": pergunte o que está impedindo a decisão. Para "já tenho seguro": ofereça análise gratuita para ver se pode economizar.',
      venda_por_cenario: 'Apresente cenários concretos: "se acontecer um acidente, o seguro cobre X". Personalize pelo veículo e perfil do cliente. Faça o cliente visualizar a proteção, não o custo.',
      urgencia_suave: 'Mencione que os preços das seguradoras variam diariamente. Ofereça travar o preço da cotação por 48h. Nunca pressione de forma agressiva.',
      fechamento: 'Resuma os benefícios escolhidos, confirme os dados, e peça confirmação de forma direta: "Posso gerar o boleto?" ou "Prefere pagar no débito ou crédito?". Facilite ao máximo.',
    },
    defaultHardRules: {
      blockExpiredLicense: true,
      requireCrlvForQuote: true,
      maxInactivityHours: 48,
      escalateToHumanScore: 8,
    },
    funnelSteps: [
      {
        key: 'NOVO_LEAD',
        label: 'Novo Contato',
        objective: 'Receber o cliente com cordialidade e identificar se é seguro novo ou renovação.',
        requiredFields: [],
        salesBlockKey: 'quebra_de_gelo',
        fallbackMessage: 'Olá! Seja bem-vindo(a). Me conta, você está buscando um seguro novo ou quer renovar o atual?',
      },
      {
        key: 'COLETAR_NOME',
        label: 'Coletar Nome',
        objective: 'Solicitar o nome completo do cliente de forma natural.',
        requiredFields: ['name'],
        fallbackMessage: 'Pode me informar seu nome completo, por favor?',
      },
      {
        key: 'SOLICITAR_CNH',
        label: 'Solicitar CNH',
        objective: 'Solicitar a foto da CNH para preencher os dados automaticamente e agilizar a cotação.',
        requiredFields: ['cpf', 'birthDate'],
        salesBlockKey: 'reducao_atrito',
        fallbackMessage: 'Para calcular o melhor preço para você, me manda a foto da sua CNH 📸',
      },
      {
        key: 'SOLICITAR_CRLV',
        label: 'Solicitar CRLV',
        objective: 'Solicitar o documento do veículo (CRLV) para completar os dados do seguro.',
        requiredFields: ['plate', 'brandModel'],
        salesBlockKey: 'reducao_atrito',
        fallbackMessage: 'Ótimo! Agora me manda o documento do veículo (CRLV) para eu calcular o valor exato 🚗',
      },
      {
        key: 'SOLICITAR_APOLICE',
        label: 'Solicitar Apólice',
        objective: 'Solicitar a apólice atual para analisar coberturas e oferecer renovação competitiva.',
        requiredFields: [],
        fallbackMessage: 'Consegue me enviar uma foto da sua apólice atual?',
      },
      {
        key: 'AGUARDANDO_COTACAO',
        label: 'Aguardando Cotação',
        objective: 'Informar que está calculando nas seguradoras parceiras e criar expectativa positiva.',
        requiredFields: [],
        salesBlockKey: 'gatilhos_mentais',
        fallbackMessage: 'Perfeito! Já vou calcular nas nossas seguradoras parceiras e te envio o melhor preço em instantes 🔍',
      },
      {
        key: 'APRESENTAR_PROPOSTA',
        label: 'Apresentar Proposta',
        objective: 'Apresentar a melhor cotação de forma clara, destacando coberturas e benefícios.',
        requiredFields: [],
        salesBlockKey: 'venda_por_cenario',
        fallbackMessage: 'Tenho ótimas opções para você! Vou te apresentar o melhor custo-benefício.',
      },
      {
        key: 'NEGOCIACAO',
        label: 'Negociação',
        objective: 'Contornar objeções de forma consultiva e manter o interesse do cliente.',
        requiredFields: [],
        salesBlockKey: 'objecoes',
        fallbackMessage: 'Entendo sua preocupação. Me conta o que está impedindo a sua decisão para eu poder te ajudar melhor.',
      },
      {
        key: 'FECHAMENTO',
        label: 'Fechamento',
        objective: 'Concluir a venda de forma direta e facilitar o pagamento.',
        requiredFields: [],
        salesBlockKey: 'fechamento',
        fallbackMessage: 'Ótimo! Posso gerar a proposta final para você agora?',
      },
    ],
    leadFields: [
      { key: 'name', label: 'Nome completo', required: true, type: 'text' },
      { key: 'cpf', label: 'CPF', required: true, type: 'cpf' },
      { key: 'birthDate', label: 'Data de nascimento', required: true, type: 'date' },
      { key: 'phone', label: 'Telefone', required: true, type: 'phone' },
      { key: 'plate', label: 'Placa', required: true, type: 'text' },
      { key: 'brandModel', label: 'Marca/Modelo', required: false, type: 'text' },
      { key: 'insuranceType', label: 'Tipo de seguro', required: false, type: 'select', options: ['Novo', 'Renovação'] },
    ],
    wizardQuestions: [
      {
        id: 'insurers',
        label: 'Quais seguradoras você trabalha?',
        type: 'multiselect',
        options: ['Porto Seguro', 'Tokio Marine', 'Allianz', 'Bradesco Seguros', 'SulAmérica', 'HDI', 'Mapfre', 'Azul Seguros', 'Liberty', 'Chubb'],
        required: true,
        contextKey: 'insurers',
        helpText: 'Selecione todas as seguradoras com que sua corretora tem parceria.',
      },
      {
        id: 'insuranceTypes',
        label: 'Quais tipos de seguro você oferece?',
        type: 'multiselect',
        options: ['Seguro Auto', 'Seguro Moto', 'Seguro Caminhão', 'Frota', 'Seguro Vida', 'Residencial'],
        required: true,
        contextKey: 'insuranceTypes',
        helpText: 'Selecione os produtos que seu agente pode oferecer.',
      },
      {
        id: 'workingHours',
        label: 'Horário de atendimento',
        type: 'text',
        placeholder: 'Ex: Segunda a Sexta, 8h às 18h',
        required: false,
        contextKey: 'workingHours',
        helpText: 'O agente informará clientes que entrem em contato fora desse horário.',
      },
    ],
    previewConversation: [
      { sender: 'user', text: 'Oi, quero fazer um seguro para meu carro' },
      { sender: 'ai', text: 'Olá! Que ótimo 😊 Você está buscando um seguro novo ou quer renovar o atual?', step: 'NOVO_LEAD' },
      { sender: 'user', text: 'Seguro novo' },
      { sender: 'ai', text: 'Para eu te passar o melhor preço já, me manda a foto da sua CNH 📸', step: 'SOLICITAR_CNH' },
    ],
    lockedFields: ['hardRules.blockExpiredLicense', 'hardRules.requireCrlvForQuote'],
    suggestedInsurers: ['Porto Seguro', 'Tokio Marine', 'Allianz', 'Bradesco Seguros', 'SulAmérica'],
  },

  // ─── Imobiliária ─────────────────────────────────────────────────────────────
  {
    id: 'imobiliaria',
    segment: 'imobiliaria',
    name: 'Imobiliária',
    description: 'Agente especializado em captação e qualificação de leads para compra, venda e aluguel de imóveis.',
    version: 1,
    publishedAt: '2026-05-16T00:00:00.000Z',
    publishedBy: 'platform',
    defaultPersona: {
      name: 'Sofia',
      role: 'Consultora Imobiliária',
      tone: 'profissional, empática e orientada a soluções',
      usesFormalTreatment: false,
    },
    defaultSalesBlocks: {
      quebra_de_gelo: 'Receba o cliente com entusiasmo e mostre que entende o momento importante que é comprar ou alugar um imóvel. Pergunte o que está buscando para personalizar o atendimento.',
      primeiro_atendimento: 'Demonstre conhecimento do mercado local. Mencione que tem acesso a imóveis exclusivos e que trabalha com as melhores condições de financiamento.',
      reducao_atrito: 'Quando o cliente hesitar em fornecer dados, explique que é para filtrar exatamente os imóveis que atendem ao perfil — evitando perda de tempo.',
      gatilhos_mentais: 'Use escassez real (imóveis com alta demanda), prova social (famílias atendidas na região), e urgência de mercado (tendência de valorização).',
      objecoes: 'Para "não tenho certeza": mostre opções variadas sem compromisso. Para "financiamento é complicado": ofereça simulação gratuita. Para "preço alto": apresente outras opções dentro do orçamento.',
      venda_por_cenario: 'Faça o cliente imaginar a rotina no novo imóvel: "a escola fica a 3 minutos", "tem vaga coberta para 2 carros". Personalize pelo perfil familiar.',
      urgencia_suave: 'Mencione outros clientes interessados no mesmo imóvel (quando verdadeiro) ou a valorização prevista na região. Nunca pressione de forma agressiva.',
      fechamento: 'Agende a visita de forma direta: "Posso marcar uma visita para você conhecer pessoalmente?" Ofereça 2 opções de horário para facilitar a decisão.',
    },
    defaultHardRules: {
      blockExpiredLicense: false,
      requireCrlvForQuote: false,
      maxInactivityHours: 72,
      escalateToHumanScore: 7,
    },
    funnelSteps: [
      {
        key: 'NOVO_LEAD',
        label: 'Novo Contato',
        objective: 'Identificar se o cliente quer comprar, vender ou alugar, e qual o perfil do imóvel desejado.',
        requiredFields: [],
        salesBlockKey: 'quebra_de_gelo',
        fallbackMessage: 'Olá! Seja bem-vindo(a). Você está procurando comprar, alugar ou tem um imóvel para vender?',
      },
      {
        key: 'COLETAR_NOME',
        label: 'Coletar Nome',
        objective: 'Solicitar o nome do cliente para personalizar o atendimento.',
        requiredFields: ['name'],
        fallbackMessage: 'Qual é o seu nome, por favor?',
      },
      {
        key: 'IDENTIFICAR_INTENCAO',
        label: 'Qualificar Perfil',
        objective: 'Entender o orçamento, região desejada, número de quartos e urgência da decisão.',
        requiredFields: [],
        salesBlockKey: 'primeiro_atendimento',
        fallbackMessage: 'Para eu encontrar as melhores opções para você, qual região você prefere e qual é o orçamento aproximado?',
      },
      {
        key: 'APRESENTAR_PROPOSTA',
        label: 'Apresentar Imóveis',
        objective: 'Apresentar as opções mais adequadas ao perfil e agendar visita.',
        requiredFields: [],
        salesBlockKey: 'venda_por_cenario',
        fallbackMessage: 'Tenho opções excelentes que combinam com o que você busca! Posso agendar uma visita para você conhecer?',
      },
      {
        key: 'NEGOCIACAO',
        label: 'Negociação',
        objective: 'Contornar objeções e manter o interesse do cliente.',
        requiredFields: [],
        salesBlockKey: 'objecoes',
        fallbackMessage: 'Entendo. Me conta o que está impedindo a decisão para eu poder te ajudar melhor.',
      },
      {
        key: 'FECHAMENTO',
        label: 'Fechamento',
        objective: 'Concluir o agendamento da visita ou iniciar a proposta formal.',
        requiredFields: [],
        salesBlockKey: 'fechamento',
        fallbackMessage: 'Quando você pode visitar o imóvel? Tenho disponibilidade hoje à tarde ou amanhã de manhã.',
      },
    ],
    leadFields: [
      { key: 'name', label: 'Nome completo', required: true, type: 'text' },
      { key: 'phone', label: 'Telefone', required: true, type: 'phone' },
      { key: 'email', label: 'E-mail', required: false, type: 'text' },
    ],
    wizardQuestions: [
      {
        id: 'propertyTypes',
        label: 'Quais tipos de imóvel você trabalha?',
        type: 'multiselect',
        options: ['Apartamento', 'Casa', 'Terreno', 'Sala Comercial', 'Galpão', 'Kitnet', 'Cobertura', 'Chácara'],
        required: true,
        contextKey: 'propertyTypes',
        helpText: 'Selecione todos os tipos que seu portfólio inclui.',
      },
      {
        id: 'operationTypes',
        label: 'Quais operações você realiza?',
        type: 'multiselect',
        options: ['Venda', 'Aluguel'],
        required: true,
        contextKey: 'operationTypes',
        helpText: 'Compra e venda, aluguel ou ambos?',
      },
      {
        id: 'serviceAreas',
        label: 'Quais regiões/bairros você atende?',
        type: 'textarea',
        placeholder: 'Ex: Zona Sul de São Paulo, bairros Vila Mariana, Moema, Ibirapuera',
        required: false,
        contextKey: 'serviceAreas',
        helpText: 'O agente usará essa informação para qualificar leads por localização.',
      },
      {
        id: 'workingHours',
        label: 'Horário de atendimento',
        type: 'text',
        placeholder: 'Ex: Segunda a Sábado, 9h às 18h',
        required: false,
        contextKey: 'workingHours',
      },
    ],
    previewConversation: [
      { sender: 'user', text: 'Oi, vi um anúncio de apartamento' },
      { sender: 'ai', text: 'Olá! Ótimo, temos ótimas opções disponíveis 😊 Você está buscando para comprar ou alugar?', step: 'NOVO_LEAD' },
      { sender: 'user', text: 'Comprar' },
      { sender: 'ai', text: 'Perfeito! Para eu filtrar as melhores opções, qual região você prefere e qual é o orçamento aproximado?', step: 'IDENTIFICAR_INTENCAO' },
    ],
    lockedFields: [],
  },

  // ─── Clínica Odontológica ─────────────────────────────────────────────────────
  {
    id: 'clinica_odontologica',
    segment: 'clinica_odontologica',
    name: 'Clínica Odontológica',
    description: 'Agente especializado em captação e agendamento de consultas odontológicas. Qualifica o paciente e agenda a avaliação inicial.',
    version: 1,
    publishedAt: '2026-05-16T00:00:00.000Z',
    publishedBy: 'platform',
    defaultPersona: {
      name: 'Beatriz',
      role: 'Recepcionista da Clínica',
      tone: 'acolhedora, clara e tranquilizadora',
      usesFormalTreatment: false,
    },
    defaultSalesBlocks: {
      quebra_de_gelo: 'Receba o paciente com acolhimento e empatia. Demonstre que a clínica se preocupa com o bem-estar e que o processo é simples e sem dor.',
      primeiro_atendimento: 'Explique brevemente os serviços disponíveis e destaque que a avaliação inicial é gratuita (se aplicável). Transmita confiança e profissionalismo.',
      reducao_atrito: 'Quando o paciente hesitar por medo ou custo, normalize a situação: "muitos pacientes têm essa dúvida". Destaque o parcelamento e a cobertura de planos.',
      gatilhos_mentais: 'Use saúde como urgência genuína: problemas dentários pioram com o tempo. Destaque antes/depois de casos similares (sem identificar pacientes).',
      objecoes: 'Para "muito caro": apresente parcelamento e planos. Para "tenho medo": descreva o processo tranquilizador. Para "não tenho tempo": ofereça horários alternativos.',
      venda_por_cenario: 'Faça o paciente imaginar o resultado: "em X sessões você terá o sorriso que sempre quis". Personalize pelo tratamento desejado.',
      urgencia_suave: 'Mencione que a agenda está ficando cheia e que a avaliação gratuita tem vagas limitadas. Ofereça o próximo horário disponível.',
      fechamento: 'Confirme o agendamento de forma direta: "Posso te agendar para [data/hora]?" Envie o endereço e lembrete de confirmação.',
    },
    defaultHardRules: {
      blockExpiredLicense: false,
      requireCrlvForQuote: false,
      maxInactivityHours: 48,
      escalateToHumanScore: 7,
    },
    funnelSteps: [
      {
        key: 'NOVO_LEAD',
        label: 'Novo Contato',
        objective: 'Entender o motivo do contato e qual tratamento o paciente busca.',
        requiredFields: [],
        salesBlockKey: 'quebra_de_gelo',
        fallbackMessage: 'Olá! Seja bem-vindo(a)! Como posso te ajudar? Qual tratamento você está buscando?',
      },
      {
        key: 'COLETAR_NOME',
        label: 'Coletar Nome',
        objective: 'Solicitar o nome do paciente para personalizar o atendimento.',
        requiredFields: ['name'],
        fallbackMessage: 'Qual é o seu nome, por favor?',
      },
      {
        key: 'IDENTIFICAR_INTENCAO',
        label: 'Qualificar Necessidade',
        objective: 'Identificar o tratamento desejado, urgência e se possui plano odontológico.',
        requiredFields: [],
        salesBlockKey: 'primeiro_atendimento',
        fallbackMessage: 'Você tem algum plano odontológico ou prefere atendimento particular?',
      },
      {
        key: 'APRESENTAR_PROPOSTA',
        label: 'Apresentar Opções',
        objective: 'Apresentar o tratamento adequado e o valor/condições, convidando para avaliação.',
        requiredFields: [],
        salesBlockKey: 'venda_por_cenario',
        fallbackMessage: 'Temos exatamente o que você precisa! Posso agendar uma avaliação gratuita para você?',
      },
      {
        key: 'NEGOCIACAO',
        label: 'Contornar Objeções',
        objective: 'Lidar com objeções de custo, medo ou disponibilidade.',
        requiredFields: [],
        salesBlockKey: 'objecoes',
        fallbackMessage: 'Entendo. Me conta sua principal dúvida para eu te ajudar.',
      },
      {
        key: 'FECHAMENTO',
        label: 'Agendar Consulta',
        objective: 'Confirmar o agendamento da consulta ou avaliação.',
        requiredFields: [],
        salesBlockKey: 'fechamento',
        fallbackMessage: 'Qual o melhor dia e horário para você? Temos disponibilidade esta semana.',
      },
    ],
    leadFields: [
      { key: 'name', label: 'Nome completo', required: true, type: 'text' },
      { key: 'phone', label: 'Telefone', required: true, type: 'phone' },
      { key: 'email', label: 'E-mail', required: false, type: 'text' },
    ],
    wizardQuestions: [
      {
        id: 'specialties',
        label: 'Quais especialidades sua clínica oferece?',
        type: 'multiselect',
        options: ['Clínico Geral', 'Ortodontia', 'Implantes', 'Estética', 'Endodontia', 'Periodontia', 'Pediatria', 'Cirurgia', 'Prótese'],
        required: true,
        contextKey: 'specialties',
        helpText: 'O agente mencionará apenas os tratamentos disponíveis.',
      },
      {
        id: 'planTypes',
        label: 'Quais planos odontológicos você aceita?',
        type: 'multiselect',
        options: ['Amil Dental', 'Bradesco Dental', 'Odontoprev', 'MetLife', 'Porto Seguro Odonto', 'SulAmérica Odonto', 'Não aceito planos'],
        required: false,
        contextKey: 'planTypes',
        helpText: 'Selecione "Não aceito planos" se for clínica apenas particular.',
      },
      {
        id: 'workingHours',
        label: 'Horário de atendimento',
        type: 'text',
        placeholder: 'Ex: Segunda a Sexta, 8h às 19h, Sábado 8h às 13h',
        required: false,
        contextKey: 'workingHours',
      },
    ],
    previewConversation: [
      { sender: 'user', text: 'Oi, quero fazer clareamento dental' },
      { sender: 'ai', text: 'Olá! Que ótimo, adoramos cuidar do seu sorriso 😊 Você tem plano odontológico ou prefere atendimento particular?', step: 'IDENTIFICAR_INTENCAO' },
      { sender: 'user', text: 'Particular' },
      { sender: 'ai', text: 'Perfeito! Posso agendar uma avaliação gratuita para passarmos o orçamento exato. Qual o melhor dia para você?', step: 'APRESENTAR_PROPOSTA' },
    ],
    lockedFields: [],
  },

  // ─── Concessionária ──────────────────────────────────────────────────────────
  {
    id: 'concessionaria',
    segment: 'concessionaria',
    name: 'Concessionária de Veículos',
    description: 'Agente especializado em qualificação de leads para compra de veículos novos e seminovos. Agenda test drive e apresenta condições de financiamento.',
    version: 1,
    publishedAt: '2026-05-16T00:00:00.000Z',
    publishedBy: 'platform',
    defaultPersona: {
      name: 'Rafael',
      role: 'Consultor de Vendas',
      tone: 'entusiasmado, consultivo e objetivo',
      usesFormalTreatment: false,
    },
    defaultSalesBlocks: {
      quebra_de_gelo: 'Receba o cliente com entusiasmo genuíno. Pergunte qual modelo ou segmento de veículo ele está buscando para personalizar desde o início.',
      primeiro_atendimento: 'Demonstre conhecimento dos veículos disponíveis. Mencione condições especiais de financiamento, garantia de fábrica e o processo simplificado de compra.',
      reducao_atrito: 'Quando o cliente hesitar, ofereça test drive sem compromisso. "Você pode experimentar antes de decidir — sem pressão nenhuma."',
      gatilhos_mentais: 'Use oferta limitada (estoque do modelo), condições especiais de lançamento e custo-benefício comparado ao custo de manutenção do veículo atual.',
      objecoes: 'Para "vou pesquisar mais": ofereça comparativo já pronto. Para "financiamento caro": apresente simulação personalizada. Para "meu carro atual ainda está bom": fale sobre valorização na troca.',
      venda_por_cenario: 'Faça o cliente imaginar na direção do veículo: conforto, tecnologia, economia de combustível. Personalize pelos itens que ele valoriza.',
      urgencia_suave: 'Mencione disponibilidade de estoque, condições de financiamento com prazo, ou desconto válido até determinada data. Nunca invente.',
      fechamento: 'Proponha o test drive ou visita como próximo passo natural: "Quando você pode passar para experimentar o carro?" Ofereça 2 opções de horário.',
    },
    defaultHardRules: {
      blockExpiredLicense: false,
      requireCrlvForQuote: false,
      maxInactivityHours: 48,
      escalateToHumanScore: 8,
    },
    funnelSteps: [
      {
        key: 'NOVO_LEAD',
        label: 'Novo Contato',
        objective: 'Identificar o interesse (veículo novo ou seminovo) e qual modelo ou segmento atrai o cliente.',
        requiredFields: [],
        salesBlockKey: 'quebra_de_gelo',
        fallbackMessage: 'Olá! Seja bem-vindo(a)! Você está buscando um veículo novo ou seminovo?',
      },
      {
        key: 'COLETAR_NOME',
        label: 'Coletar Nome',
        objective: 'Solicitar o nome do cliente.',
        requiredFields: ['name'],
        fallbackMessage: 'Qual é o seu nome, por favor?',
      },
      {
        key: 'IDENTIFICAR_INTENCAO',
        label: 'Qualificar Perfil',
        objective: 'Entender modelo desejado, orçamento, forma de pagamento e se tem veículo para troca.',
        requiredFields: [],
        salesBlockKey: 'primeiro_atendimento',
        fallbackMessage: 'Para te mostrar as melhores opções, você pensa em financiar ou pagar à vista? E tem algum veículo para dar na troca?',
      },
      {
        key: 'APRESENTAR_PROPOSTA',
        label: 'Apresentar Veículos',
        objective: 'Apresentar os modelos adequados ao perfil e convidar para test drive.',
        requiredFields: [],
        salesBlockKey: 'venda_por_cenario',
        fallbackMessage: 'Tenho opções perfeitas para você! Posso agendar um test drive para você conhecer pessoalmente?',
      },
      {
        key: 'NEGOCIACAO',
        label: 'Negociação',
        objective: 'Contornar objeções sobre preço, financiamento ou comparação com concorrentes.',
        requiredFields: [],
        salesBlockKey: 'objecoes',
        fallbackMessage: 'Entendo. Me conta sua principal dúvida para eu te apresentar a melhor solução.',
      },
      {
        key: 'FECHAMENTO',
        label: 'Agendar Visita / Test Drive',
        objective: 'Confirmar o agendamento da visita ou test drive.',
        requiredFields: [],
        salesBlockKey: 'fechamento',
        fallbackMessage: 'Quando você pode passar na concessionária? Tenho disponibilidade hoje à tarde ou amanhã.',
      },
    ],
    leadFields: [
      { key: 'name', label: 'Nome completo', required: true, type: 'text' },
      { key: 'phone', label: 'Telefone', required: true, type: 'phone' },
      { key: 'email', label: 'E-mail', required: false, type: 'text' },
    ],
    wizardQuestions: [
      {
        id: 'brands',
        label: 'Quais marcas sua concessionária vende?',
        type: 'multiselect',
        options: ['Chevrolet', 'Volkswagen', 'Fiat', 'Toyota', 'Honda', 'Hyundai', 'Renault', 'Ford', 'Jeep', 'Mitsubishi', 'Nissan', 'Kia', 'BMW', 'Mercedes-Benz', 'Audi'],
        required: true,
        contextKey: 'brands',
        helpText: 'O agente mencionará apenas as marcas que você trabalha.',
      },
      {
        id: 'vehicleTypes',
        label: 'Quais tipos de veículo você vende?',
        type: 'multiselect',
        options: ['Hatch', 'Sedã', 'SUV', 'Picape', 'Van', 'Elétrico', 'Híbrido', 'Seminovos'],
        required: true,
        contextKey: 'vehicleTypes',
        helpText: 'Selecione os segmentos disponíveis.',
      },
      {
        id: 'workingHours',
        label: 'Horário de atendimento',
        type: 'text',
        placeholder: 'Ex: Segunda a Sábado, 9h às 18h',
        required: false,
        contextKey: 'workingHours',
      },
    ],
    previewConversation: [
      { sender: 'user', text: 'Oi, quero comprar um SUV' },
      { sender: 'ai', text: 'Olá! Ótima escolha 🚗 Você prefere novo ou seminovo? E pensa em financiar ou pagar à vista?', step: 'IDENTIFICAR_INTENCAO' },
      { sender: 'user', text: 'Novo, financiar' },
      { sender: 'ai', text: 'Perfeito! Tenho ótimas opções com condições especiais. Quando você pode passar para um test drive?', step: 'APRESENTAR_PROPOSTA' },
    ],
    lockedFields: [],
  },
];
