import { pgTable, text, boolean, integer, jsonb, timestamp, index } from 'drizzle-orm/pg-core';

export const organizations = pgTable('organizations', {
  id: text('id').primaryKey(),
  nomeRazaoSocial: text('nome_razao_social').notNull(),
  nomeFantasia: text('nome_fantasia'),
  cnpj: text('cnpj').notNull(),
  emailCorporativo: text('email_corporativo').notNull(),
  telefone: text('telefone'),
  slug: text('slug').notNull().unique(),
  logoUrl: text('logo_url'),
  planoSaas: text('plano_saas').notNull(),
  limiteUsuarios: integer('limite_usuarios').notNull(),
  limiteLeadsMes: integer('limite_leads_mes').notNull(),
  limiteStorageMb: integer('limite_storage_mb').notNull(),
  status: text('status').notNull(),
  trialExpiraEm: timestamp('trial_expira_em', { withTimezone: true }),
  timezone: text('timezone').notNull(),
  idioma: text('idioma').notNull(),
  ownerUserId: text('owner_user_id'),
  configuracoes: jsonb('configuracoes').notNull().default({}),
  fiscalSettings: jsonb('fiscal_settings'),
  certificate: jsonb('certificate'),
  fiscalServices: jsonb('fiscal_services'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  organizationId: text('organization_id').references(() => organizations.id),
  email: text('email').notNull(),
  name: text('name').notNull(),
  phone: text('phone'),
  role: text('role').notNull(),
  userType: text('user_type').notNull(),
  profileId: text('profile_id'),
  permissions: jsonb('permissions').notNull(),
  cargo: text('cargo'),
  photoUrl: text('photo_url'),
  status: text('status').notNull(),
  onboardingCompleted: boolean('onboarding_completed'),
  metrics: jsonb('metrics'),
  activity: jsonb('activity'),
  theme: text('theme'),
  chatPreferences: jsonb('chat_preferences'),
  superadmin: boolean('superadmin').notNull().default(false),
  lastAccess: timestamp('last_access', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index('idx_users_org').on(t.organizationId),
]);

export const accessProfiles = pgTable('access_profiles', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  description: text('description'),
  isActive: boolean('is_active').notNull().default(true),
  leadVisibility: text('lead_visibility').notNull(),
  permissions: jsonb('permissions').notNull(),
  menuPermissions: jsonb('menu_permissions').notNull().default([]),
  fieldPermissions: jsonb('field_permissions').notNull().default([]),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
